### ISSUE TITLE
Exclude Jackson from distribution

### ISSUE THREAD

**Issue by ivanyu** [Aiven-Open/tiered-storage-for-apache-kafka#254]
Jackson is present in Kafka, so it shouldn't be included in the plugin distribution.

**Comment by jeqo** [comment]
Some additional info: 
Jackson is defined as compileOnly, but release includes 2 versions:
- 2.15.0 from jackson-datatype-jdk8
- 2.12.7 from aws-java-sdk:1.12.418
  - Latest version hasn't upgrade neither: https://github.com/aws/aws-sdk-java/blob/ec11e09db6976b763726454f79893c847de1129e/pom.xml#L391-L392 

Also, Kafka 3.3 is using jackson 2.13.3 
https://github.com/aiven/kafka/blob/eed9192e8ad0230d58184939a64afee90dc0dae8/gradle/dependencies.gradle#L70

As Kafka is using a specific class loader, I guess we can bring our own Jackson dependency? We could create distributions for each storage backend (e.g. Azure uses jackson 2.15).

**Comment by ivanyu** [comment]
> As Kafka is using a specific class loader, I guess we can bring our own Jackson dependency

Yes, you're right. So, we can close the ticket then :)
