### ISSUE TITLE
Tiered Storage Plugin Implementation for Azure Blob Storage

### ISSUE THREAD

**Issue by piyush-gupta1999** [Aiven-Open/tiered-storage-for-apache-kafka#421]
# What is currently missing?

Currently, this implementation is missing a plugin for Azure Blob Storage. 

# How could this be improved?
We need a TS plugin to push data to Azure Blob Storage.

# Is this a feature you would work on yourself?
I can work on this feature. I need some guidance to work.

**Comment by ivanyu** [comment]
Hi @piyush-gupta1999 
Thanks for your interest in the plugin!
The team is working on it at the moment and soon the PR will be created. You're welcome to review!

**Comment by piyush-gupta1999** [comment]
Hi @ivanyu, Thank you for your quick response. I am from the HDInsight Team from Microsoft India. Our Team offers Managed Service Kafka on Azure Infra. I am interested in understanding which storage accounts you are offering from Azure. Example - WASB, ABFS.

**Comment by ivanyu** [comment]
And here comes the PR: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/424
@piyush-gupta1999 if you have a chance to look, your review is most welcome!

**Comment by ivanyu** [comment]
> I am interested in understanding which storage accounts you are offering from Azure. Example - WASB, ABFS

If I understand this right, we're basically focusing on Blob Storage on HTTP.
