### ISSUE TITLE
error in consumer-perf-test

### ISSUE THREAD

**Issue by freshtang** [Aiven-Open/tiered-storage-for-apache-kafka#479]
# What happened?

1.create tieredTopic
`bin/kafka-producer-perf-test.sh     --topic tieredTopic0105 --num-records=100000000 --throughput 100000 --record-size 1000     --producer-props acks=1 batch.size=16384 bootstrap.servers=localhost:9092`

2.produce messages with kafka-producer-perf-test
`bin/kafka-producer-perf-test.sh     --topic test --num-records=100000000 --throughput 100000 --record-size 1000     --producer-props acks=1 batch.size=16384 bootstrap.servers=localhost:9092`

3.consume with kafka-consumer-perf-test.sh
`bin/kafka-consumer-perf-test.sh --topic  tieredTopic0105  --bootstrap-server localhost:9092 --messages 100000 --group test`

![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/23481271/3271e870-26a6-4efd-94f9-0a63f202da18)

![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/23481271/26ef2d80-b78b-463d-a4bd-b08436835985)

# What else do we need to know?
broker uses [aliyun oss]( https://www.aliyun.com/product/oss?spm=5176.28508143.J_4VYgf18xNlTAyFFbOuOQe.161.716f154aSmdgXJ&scm=20140722.X_data-47ed1f95c8b1f5f652d4._.V_1) as s3

**Comment by jeqo** [comment]
@freshtang just as reference, this is caused because of how timeouts are handled on the broker side, see #483 for future resolution. 

As a workaround, consumers can increase their `fetch.max.wait.ms` to e.g. 2sec
