### ISSUE TITLE
When is the next version expected to be released, I am currently unable to download snapshot.

### ISSUE THREAD

**Issue by funky-eyes** [Aiven-Open/tiered-storage-for-apache-kafka#498]
# What can we help you with?

May I ask why I try to download the snapshot in release and it keeps returning 502, how can I download it successfully? Or when will the official version be released?
![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/19943636/09f1cf6c-00da-460f-b3e2-f7d571a0ca07)

# Where would you expect to find this information?

**Comment by webchick** [comment]
Hey there, just checking that this error resolved itself and you got what you needed?
