### ISSUE TITLE
Disk space not released

### ISSUE THREAD

**Issue by funky-eyes** [Aiven-Open/tiered-storage-for-apache-kafka#513]
# What can we help you with?
I found that after running for a while, the disk occupancy is not actually released, I am using raft cluster mode and I don't know how to troubleshoot it
![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/19943636/b604bab5-a30b-406a-8e69-7be688fd2dc9)
Why is this happening? I found that after I restarted the node again, the disk space was freed up

# Where would you expect to find this information?

**Comment by funky-eyes** [comment]
![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/19943636/0085a316-ba57-4efc-acfc-7163ec30781e)
I found a very large number of files that were deleted but still referenced without freeing up space

**Comment by funky-eyes** [comment]
I've clearly seen this file in s3, but locally he's still not cleaned up!

**Comment by ivanyu** [comment]
Hi @funky-eyes 
By "not cleaned up" you mean they exist as "<old_file_name>.deleted"?

**Comment by funky-eyes** [comment]
> Hi @funky-eyes By "not cleaned up" you mean they exist as "<old_file_name>.deleted"?

They no longer exist in the catalogue. Can you see the picture I sent? The deleted file is still being referenced, resulting in the disk space not released.

**Comment by funky-eyes** [comment]
> Hi @funky-eyes By "not cleaned up" you mean they exist as "<old_file_name>.deleted"?

Could this be due to the operating system? I've noticed that after a while, the disk is actually freed, but it's minutes or even tens of minutes before it's freed!

**Comment by funky-eyes** [comment]
I set a topic again, remote.storage.enable=false, retention.ms=180000, and when it is cleaned up on disk, the disk space is freed up almost in real-time

**Comment by funky-eyes** [comment]
![image](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/assets/19943636/29d769c1-0f25-4968-a896-cdc6cfe5804c)
I waited for more than ten hours and the space still hasn't been freed, which is significantly different from the performance of a topic without tiered storage, where some files that no longer exist on disk are still being referenced by kafka

**Comment by funky-eyes** [comment]
I also gave feedback on this issue in the kafka community：https://[issues.apache.org/jira/browse/KAFKA-16378](https://issues.apache.org/jira/browse/KAFKA-16378)

**Comment by ivanyu** [comment]
We're looking into this, trying to first understand if it's the plugin's or broker's problem.

**Comment by funky-eyes** [comment]
> We're looking into this, trying to first understand if it's the plugin's or broker's problem.

Thank you very much for your intervention. The cluster I deployed is in kraft mode, and the code used is the latest main branch packaged and deployed, and I found that as long as I use` jcmd pid GC.run`, the disk space occupation will be released immediately, but when there is no gc, some files are not released, and there is no error-level log output in the log.

**Comment by funky-eyes** [comment]
And I'm using s3's tiered storage implementation

**Comment by ivanyu** [comment]
Seems to be really an issue in the plugin. Will be fixed in https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/pull/516

**Comment by funky-eyes** [comment]
> Seems to be really an issue in the plugin. Will be fixed in #516

Thanks, I'll pull it up later and recompile it locally for testing.

**Comment by funky-eyes** [comment]
> Seems to be really an issue in the plugin. Will be fixed in #516

I understand that the purpose of this PR is to introduce a ClosableInputStreamHolder, which uniformly handles the closing of all InputStreams generated during the copyLogSegmentData phase, ensuring that the streams are correctly closed. Is my understanding correct?

**Comment by funky-eyes** [comment]
@ivanyu I have confirmed that this issue has been fixed by #516

**Comment by ivanyu** [comment]
> I understand that the purpose of this PR is to introduce a ClosableInputStreamHolder, which uniformly handles the closing of all InputStreams generated during the copyLogSegmentData phase, ensuring that the streams are correctly closed. Is my understanding correct?

Yeah, that's correct. We forgot to close those streams and through this the open files. They lingered open until the Java internal cleaning machinery kicks in and closes the files.

**Comment by funky-eyes** [comment]
> > I understand that the purpose of this PR is to introduce a ClosableInputStreamHolder, which uniformly handles the closing of all InputStreams generated during the copyLogSegmentData phase, ensuring that the streams are correctly closed. Is my understanding correct?
> 
> Yeah, that's correct. We forgot to close those streams and through this the open files. They lingered open until the Java internal cleaning machinery kicks in and closes the files.

Thank you for your eagerness to help.
