### ISSUE TITLE
Is there anyway can reduce the GET QPS for S3

### ISSUE THREAD

**Issue by bingkunyangvungle** [Aiven-Open/tiered-storage-for-apache-kafka#538]
# What can we help you with?

Currently in our case, the S3 Get requests are way beyond the S3 Get QPS threshold and the requests are throttled. Our GET QPS is about 10 times more that the threshold(5500 GET/sec). I tried to change the segment size and it doesn't help that much.

# Where would you expect to find this information?

Is there any suggestions or configuration that can help us to reduce the GET qps to S3?

**Comment by ivanyu** [comment]
@bingkunyangvungle could you please tell more about your workload, e.g. the number of active partitions, what are the topic config, number of active consumers, some consumer configurations?

**Comment by bingkunyangvungle** [comment]
Hi @ivanyu There're 1200 partitions and the consuming speed for msg is 300k/sec. As for the total load, it's about 15GiB/min in total for the cluster.

**Comment by funky-eyes** [comment]
Do you have caching enabled？

**Comment by ivanyu** [comment]
And generally could you please show the plugin config?

**Comment by bingkunyangvungle** [comment]
@ivanyu Sure. The followings are my plugin configs. Kind of just use the default one from the website.
```
# Remote storage configurations
remote.log.storage.system.enable=true
remote.log.storage.manager.class.path=/etc/kafka/libs/remote_storage_libs/*
remote.log.storage.manager.impl.prefix=rsm.config.
remote.log.storage.manager.class.name=io.aiven.kafka.tieredstorage.RemoteStorageManager

remote.log.metadata.manager.impl.prefix=rlmm.config.
remote.log.metadata.manager.listener.name=PLAINTEXT
rlmm.config.remote.log.metadata.topic.replication.factor=1

rsm.config.storage.backend.class=io.aiven.kafka.tieredstorage.storage.s3.S3Storage
rsm.config.chunk.size=4194304
rsm.config.key.prefix.mask=true
rsm.config.storage.s3.credentials.default=true
rsm.config.storage.s3.region=us-east-1

rsm.config.fetch.chunk.cache.class=io.aiven.kafka.tieredstorage.fetch.cache.DiskChunkCache
rsm.config.fetch.chunk.cache.path=/data/cache
# Pick some cache size, 16 GiB here:
rsm.config.fetch.chunk.cache.size=17179869184
# Prefetching size, 16 MiB here:
rsm.config.fetch.chunk.cache.prefetch.max.size=16777216
```

**Comment by ivanyu** [comment]
I would recommend looking into the following:

# Cache
Get the situation with the chunk disk cache. Check the `aiven.kafka.server.tieredstorage.cache` metrics in JMX, particularly `cache-hits`, `cache-misses`, `cache-eviction`. If there are too many cache misses and cache evictions, you probably need to increase the cache size, it's too small for your workload (it's probably even likely). You can even try this without looking into the metrics, just bump `rsm.config.fetch.chunk.cache.size` 10-100x.

# Chunk size
Downloading (as well as caching and lots of other stuff) happens in chunks. So the bigger the chunk the fewer the GET requests are issued. This won't apply to the data that are already uploaded, but surely will affect the new data. However, getting too big chunks will affect the read latency negatively (at this stage of the implementation), so you probably don't want to 10x the chunk size.

**Comment by funky-eyes** [comment]
I suspect that the cache space is set too small, leading to a large number of cache evictions, which in turn requires repeated fetching of data from S3

**Comment by bingkunyangvungle** [comment]
@ivanyu BTW, could I ask why there's so many GET requests compared to the relative smaller POST request? Say in my case, the GET request is hundreds more times than the POST request. Also I noticed that the PUT request has almost the same amount as the GET request. Could I ask what are these PUT request doing? Thank you.

**Comment by jeqo** [comment]
@bingkunyangvungle about GET vs POST requests, it's as expected: POST (uploads) are per segment (+indexes + segment manifest), and GET are range-based so to read a single segment you my need a larger amount of GET requests (e.g. segment-size / chunk size). Hundred times sounds like an expected range. Not sure which PUT operations are you referencing to.

>  So does it mean that every time the consumer consume the data, the framework will try to grab to data and store it locally, and then send it to the consumer?

Yes, the data is cached at the broker level, and can be shared by multiple consumers if they fetch data within the same range.

**Comment by jeqo** [comment]
@bingkunyangvungle I'd also expect [TS quotas](https://cwiki.apache.org/confluence/display/KAFKA/KIP-956+Tiered+Storage+Quotas), coming on 3.9, to help with operating how much data is fetched from remote storage per broker.

**Comment by bingkunyangvungle** [comment]
Hi @jeqo , FYI the following is the experiment that we conduct: 
Setup:
51 brokers(`m7g.xlarge` instance in AWS) and each with 2TB local disk. The producing speed is 2.24 GiB/s and the consuming speed is 3.17 GiB/s. 

Result:
As for the tiered storage, the copy request is about 4 req/sec and the copied bytes is about 4 GiB/s. The fetch request is about 3200 req/s and the fetched bytes is about 3.1 GiB/s. During these operations, the CPU utilization is around 40% ~ 45% and the memory usage is between 20% ~ 25%.

**Comment by bingkunyangvungle** [comment]
@jeqo , actually for the Put request for S3, it is about 20 million per day, compared to the post request, which is about 800 k per day. This are the metrics from AWS's monitoring. As for our own dashboard, I used the metrics from the client side(the plugin's metrics) `kafka_server_brokertopicmetrics_remotecopyrequests_total` and it's only about 200k requests for storing data(Post request). So do you know if there's anything wrongly configured on the plugin's side? Why there's so much differences between the metrics from the AWS and the plugin. Thank you!

**Comment by bingkunyangvungle** [comment]
Actually as I search in the log file for the upload record with the keyword: `INFO Copying log segment data completed successfully, metadata`, there's about 1.5 uploads/minute. But we have 60 brokers and that makes it about 90 uploads/minute. In total, it is about 130k uploads/day. It's not that big difference compared to 200k, but it's not close to 800k.

**Comment by jeqo** [comment]
@bingkunyangvungle thanks for the details! As we don't work with HTTP but with the AWS SDK is not straightforward to make a relation between API used and what HTTP verb is used behind; but with the information shared this gives me the idea that this may be related with the usage of Multi-Part Upload (MPU): 
- S3 Storage uses MPU to upload segments files, see https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/cf3dff2a9f99db84a5cf1c63e0b5665ada15bbaf/storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java
- S3 Storage has a configuration: `s3.multipart.upload.part.size` (default: 5MiB)
- The MPU works as a transaction so there's a call to 
  - createMultipartUpload
  - completeMultipartUpload or abortMultipartUpload
  - uploadPart

Looking at your numbers, the 800K post request seem to be related to the `createMultipartUpload` and `completeMultipartUpload`; and the put request could be linked to the `uploadPart`. You could try to increase the upload part size and get this number reduced.

**Comment by bingkunyangvungle** [comment]
Hi @jeqo thank you for pointing this out! I also found the related logs in AWS for uploading. I'll try to adjust the the upload size and see if it improve the situation, without downgrading our system's performance.

**Comment by bingkunyangvungle** [comment]
Hi @jeqo maybe one more question. Is it possible that we reduce the get request when fetching from S3? Currently our get is about 40MS/request to S3. If we can reduce this, the cost to GET from S3 will be reduced too. Thank you

**Comment by jeqo** [comment]
@bingkunyangvungle the [fetch requests are bound to the chunk size](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/443ced7be496c54ab8f19a6bb5df15c9a97f2ea3/core/src/main/java/io/aiven/kafka/tieredstorage/fetch/DefaultChunkManager.java#L54), so a higher chunk size should result in less GET requests to consume a segment

**Comment by bingkunyangvungle** [comment]
Thank you @jeqo for your response. I double checked that the `POST request` for S3 is actually the request to delete the partition because it is out of the retention time. So I guess it's hard to reduce these requests.

> @bingkunyangvungle thanks for the details! As we don't work with HTTP but with the AWS SDK is not straightforward to make a relation between API used and what HTTP verb is used behind; but with the information shared this gives me the idea that this may be related with the usage of Multi-Part Upload (MPU):
> 
> * S3 Storage uses MPU to upload segments files, see https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/blob/cf3dff2a9f99db84a5cf1c63e0b5665ada15bbaf/storage/s3/src/main/java/io/aiven/kafka/tieredstorage/storage/s3/S3MultiPartOutputStream.java
> * S3 Storage has a configuration: `s3.multipart.upload.part.size` (default: 5MiB)
> * The MPU works as a transaction so there's a call to
>   
>   * createMultipartUpload
>   * completeMultipartUpload or abortMultipartUpload
>   * uploadPart
> 
> Looking at your numbers, the 800K post request seem to be related to the `createMultipartUpload` and `completeMultipartUpload`; and the put request could be linked to the `uploadPart`. You could try to increase the upload part size and get this number reduced.

**Comment by jeqo** [comment]
@bingkunyangvungle agree, those are per segment so not much else to do. 
Thank you for the questions and feedback though; will make sure to add notes on request costs in our docs.
