### ISSUE TITLE
When can the community provide an official version?

### ISSUE THREAD

**Issue by funky-eyes** [Aiven-Open/tiered-storage-for-apache-kafka#546]
# What can we help you with?

# Where would you expect to find this information?

We have been hoping to run it in a production environment, which requires an official available version, not a snapshot version. Does the community have any plans for release?

**Comment by ivanyu** [comment]
We would like to get the final KIP line-up for Kafka 3.8 to check that there's no breaking API changes to the plugin. This should happen in a couple of days as the KIP freeze is near. After that, we'll make the first real release.

**Comment by funky-eyes** [comment]
> We would like to get the final KIP line-up for Kafka 3.8 to check that there's no breaking API changes to the plugin. This should happen in a couple of days as the KIP freeze is near. After that, we'll make the first real release.

Thank you for your response, it's really exciting!
