### ISSUE TITLE
Can the remote_log_metadata topic enable the remote.storage.enable configuration?

### ISSUE THREAD

**Issue by funky-eyes** [Aiven-Open/tiered-storage-for-apache-kafka#557]
# What can we help you with?

Because I saw in Kafka documentation that it's desired for the persistence duration of this topic to be greater than the TTL of any other topic, I think this topic might occupy a significant amount of local disk space. Therefore, I would like to store it remotely, for example, in S3.

# Where would you expect to find this information?

**Comment by ivanyu** [comment]
I think, this won't work. There's an [explicit prohibition](https://github.com/apache/kafka/blob/524ad1e14b1f3ff2c5eff703fdf3534092ca58fd/core/src/main/scala/kafka/log/UnifiedLog.scala#L1988) in the code, which guards against the chicken-egg problem: how to bootstrap the remote metadata if they are on the remote storage themselves?

**Comment by funky-eyes** [comment]
> I think, this won't work. There's an [explicit prohibition](https://github.com/apache/kafka/blob/524ad1e14b1f3ff2c5eff703fdf3534092ca58fd/core/src/main/scala/kafka/log/UnifiedLog.scala#L1988) in the code, which guards against the chicken-egg problem: how to bootstrap the remote metadata if they are on the remote storage themselves?

This means that the local disk space must reserve the size of remote_log_metadata. For example, if the TTL of my other topics is six months, remote_log_metadata must be retained for more than six months.

**Comment by funky-eyes** [comment]
@ivanyu Can __consumer_offsets topic be tiered?

**Comment by jeqo** [comment]
@funky-eyes the condition includes `Topic.isInternal` which validates against consumer offsets and transaction state topics. So, no, these topics cannot be tiered.

**Comment by jeqo** [comment]
@funky-eyes closing this, feel free to reopen if anything is unclear.
